version: "3"

services:
  web:
    container_name: techapi
    restart: always
    build: .
    ports:
      - "9000:9000"
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"